### ISSUE TITLE
Error in OpenCV for any photo different from the given example

### ISSUE THREAD

**Issue by lgabs** [deepinstruction/deepnude_official#13]
No matter what photo I put as input, the code is giving me this error, however it correctly runs for some modifications in the given example (drawing on it, changing image size) :

`Executing phase: dress_to_correct
Executing phase: correct_to_mask
Executing phase: mask_to_maskref
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    main()
  File "main.py", line 21, in main
    watermark = process(dress)
  File "/home/lgabs/Documents/b/b2/deepnude_official-master/run.py", line 140, in process
    maskref = create_maskref(mask, correct)
  File "/home/lgabs/Documents/b/b2/deepnude_official-master/opencv_transform/mask_to_maskref.py", line 37, in create_maskref
    res1 = cv2.bitwise_and(cv_correct, cv_correct, mask = green_mask_inv)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/core/src/arithm.cpp:245: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'binary_op'
`
Did anyone get this?

**Comment by niko247** [comment]
You save photo as "input.png" 512x512pixels and with bit depth 32? try to save it using Paint it works for me

**Comment by lgabs** [comment]
Thanks, it worked! But resize to this can eventually mess the photo, this can not be a parameter in the code?

**Comment by niko247** [comment]
> Thanks, it worked! But resize to this can eventually mess the photo, this can not be a parameter in the code?

I think this will be hard to achieve, as everrything is adjusted to size 512x512 but I hope in future they will solve this problem
